version: '3.8'

services:
  web.angular:
    container_name: lde.web.angular
    build:
      context: .
      dockerfile: Web/post-web/Dockerfile
    environment:
      - ANGULAR_ENVIRONMENT=Development
      - ANGULAR_URLS=http://+:5102
    depends_on:
      - post.api
      - identityserver.api
    ports:
      - 5102:5102
  identityserver.api:
    container_name: lde.identityserver.api
    build:
      context: .
      dockerfile: IdentityServerApi/IdentityServerApi.Host/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5100
      - AngularUrl=http://www.alevelwebsite.com
      - PostApi=http://www.postcreator.com:5101
      - BasketApi=http://www.alevelwebsite.com:5003
      - OrderApi=http://www.alevelwebsite.com:5004 
      - ConnectionString=server=www.postcreator.com;port=5435;database=identityserver;uid=postgres;password=postgres;
    depends_on:
      - identitypostgres
    ports:
      - 5100:5100
  post.api:
    container_name: lde.post.api
    build:
      context: .
      dockerfile: Post/Post.Host/Dockerfile
    environment:
       - ASPNETCORE_ENVIRONMENT=Development
       - ASPNETCORE_URLS=http://+:5101
       - ConnectionString=server=www.postcreator.com;port=5433;database=post;uid=postgres;password=postgres;
    depends_on:
      - postpostgres
      - identityserver.api
    ports:
      - 5101:5101    
  pgadmin4:
    image: dpage/pgadmin4
    container_name: lde.pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    depends_on:
      - identitypostgres
      - postpostgres
    ports:
      - 8001:80 
  identitypostgres:
    image: postgres
    container_name: lde.identitypostgres
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5435:5432
  postpostgres:
    image: postgres
    container_name: lde.postpostgres
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5433:5432   
  nginx:
    image: nginx
    container_name: lde.nginx
    ports:
      - 80:80
    volumes:
      - ./Web/post-web/dist:/usr/share/nginx/html 
      - ./Proxy/gateway/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - web.angular  
networks:
  default:
    driver: bridge
    internal: false
    attachable: true
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/24
          gateway: 192.168.0.4