version: '3.8'

services:
  identityserver.api:
    container_name: lde.identityserver.api
    build:
      context: .
      dockerfile: IdentityServerApi/IdentityServerApi.Host/Dockerfile
    environment:
       - ASPNETCORE_ENVIRONMENT=Development
       - ASPNETCORE_URLS=http://+:5100
       - ConnectionString=server=www.postcreator.com;port=5435;database=identityserver;uid=postgres;password=postgres;
    depends_on:
      - identitypostgres
    ports:
      - 5100:5100
  post.api:
    container_name: lde.post.api
    build:
      context: .
      dockerfile: Post/Post.Host/Dockerfile
    environment:
       - ASPNETCORE_ENVIRONMENT=Development
       - ASPNETCORE_URLS=http://+:5101
       - ConnectionString=server=www.postcreator.com;port=5433;database=posts;uid=postgres;password=postgres;
    depends_on:
      - postpostgresq
      - identityserver.api
    ports:
      - 5101:5101    
  pgadmin4:
    image: dpage/pgadmin4
    container_name: lde.pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    depends_on:
      - identitypostgres
    ports:
      - 8001:80 
  identitypostgres:
    image: postgres
    container_name: lde.identitypostgres
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5435:5432
  postpostgresq:
    image: postgres
    container_name: lde.postpostgres
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5433:5432   
networks:
  default:
    driver: bridge
    internal: false
    attachable: true
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/24
          gateway: 192.168.0.4